DELETE FROM POINTS

DELETE FROM BUDGETS

DELETE FROM CATEGORIES

DELETE FROM VILLES

INSERT INTO VILLES(Nom_Ville) VALUES(N'Bordeaux')

INSERT INTO VILLES(Nom_Ville) VALUES(N'Nantes')

INSERT INTO VILLES(Nom_Ville) VALUES(N'Toulouse')

